### ISSUE TITLE
Out of date

### ISSUE THREAD

**Issue by lurch** [waveform80/rpi-gpio#1]
I'm not sure what purpose this clone-repo serves, but it's now lagging behind https://sourceforge.net/projects/raspberry-gpio-python/ (which is at version 0.6.2, whilst this repo is at 0.6.1)

**Comment by waveform80** [comment]
Hehe -  the purpose is to have something a smidgen better than SF's godawful code viewer (the laundry list of complaints about which I'll avoid repeating here). I'll sync it at some point when I need to refer to it again, but that's literally the purpose it exists.

**Comment by lurch** [comment]
Are there no GitHub plugins / addons which can auto-sync from SF to GH?

Ah... just did a search and found https://sfxpt.wordpress.com/2013/02/17/git-mirroring-from-sourceforge-to-github/ but it seems all the solutions either rely on a cron-job somewhere, or modifying the source repo to automatically push to the mirror repo, neither of which we want to do in this case.

I'll close this issue and let you update your mirror when the need arises :-)
